services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123   # 원하는 비번으로 변경
      MYSQL_DATABASE: spring_db          # 사용할 DB 이름
    ports:
      - "3307:3306" #내 로컬을 3306 이미 mysql이 먹고 있어서 3307로 변경
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p password123" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Spring Boot에서 사용할 DB 접속 정보 환경변수
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/spring_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql-data:
