services:

  cache:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - knowledge_network

  application:
    container_name: knowledge_be
    image: knowledge_be
    ports:
      - 8080:8080
    depends_on:
      - cache
    env_file:
      - .env
    networks:
      - knowledge_network

volumes:
    redis_data:

networks:
  knowledge_network:
    driver: bridge
