spring:
  datasource:
    url: "jdbc:mysql://db:3306/naver?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      #ddl-auto: update
      hbm2ddl.auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessTokenExpirationMinutes: 30
  refreshTokenExpirationDays: 30