spring:
  profiles:
    active: docker

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    access-token-expiration-ms: 600000 # 10분
    refresh-token-expiration-ms: 86400000 # 24시간

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: DEBUG
