spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ceos
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    user:
      name: root
      password: root

logging:
  level:
    org.hibernate.sql : debug



server:
  port: 8081

jwt:
  access-token-expiration: 3600
  refresh-token-expiration: 604800
  secret: V3lKZEtfR2h6N1dxUmpKMGIzQnFJczBpYlZmNmp0UzQxZlN0aDRZdw
