spring:
  datasource:
    url: jdbc:mysql://localhost:3306/knowledgein
    username: root
    password: ${DB_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
  data:
    redis:
      host: localhost
      port: 6379
  jwt:
    secret: ${jwt_secret}
    access-token-validity-seconds: 86400 # 24시간
    refresh-token-validity-seconds: 604800 # 1주일