spring:
  application:
    name: knowledgeIn

  datasource:
    url: jdbc:h2:tcp://localhost/~/knowledgeIn
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: c2b691abb38430fe106f9cbd6de526a1bc8db1ae6af9ac628a0881528d6a552e
