spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ceos21
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    user:
      name: root
      password: root

logging:
  level:
    org.hibernate.sql : debug



server:
  port: 8081


