spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ceos21
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: DEBUG


